- name: "Install Borg application"
  ansible.builtin.include_tasks: install_app/main.yml

- name: "Create Borg config dirs"
  ansible.builtin.include_tasks: create_config_dirs/main.yml

- name: "Configure default Borg application settings"
  ansible.builtin.include_tasks: config_app_settings/main.yml

- name: "Create Borg utility script"
  ansible.builtin.include_tasks: create_util_script/main.yml

- name: "Create Borg user guide"
  ansible.builtin.include_tasks: create_user_guide/main.yml
  when: (borg_user_guide_dir)

- name: "Create keyfile and initialize Borg remote repo, as required"
  ansible.builtin.include_tasks: create_keyfile_init_repo/main.yml

- name: "Install automatic backup utilities"
  ansible.builtin.include_tasks: install_auto_backup_utils/main.yml
  when: enable_automatic_borg_backups

- name: "Configure automatic backups"
  ansible.builtin.include_tasks: config_auto_backups/main.yml
  when: enable_automatic_borg_backups

