- name: "Create zfs datasets for Borg config dirs"
  community.general.zfs:
    name: "{{ borg_config_dir_zpool }}{{ item }}"
    state: present
  become: true
  become_user: root
  loop:
    - "{{ borg_config_dir }}"
    - "{{ borg_keys_dir }}"
    - "{{ borg_security_dir }}"
    - "{{ borg_cache_dir }}"

